# example toml
[experiment]
name = "experiment_name"
description = "evaluation run"

[data]
data_dir = "data_dir"
test_file = "sorted_test.pt"
test_helperfile = "sorted_test_helper.pt"
test_truthfile = "test_truths.csv"
dataloader_num_workers = 4
num_classes = 451


[model]
checkpoint_path = "../results/run/model_final.pth"
inputfeature_dim = 3
num_heads = 8
embed_dim = 128
num_layers = 6
dropout = 0.1


[training]
batch_size = 64


[output]
base_path = "../results/run/"

[logging]
level = "INFO"

[wandb]
entity = "entity"
project_name = "project_name"
run_name = "run_name"
